"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "vi";

type Translations = {
  [key in Language]: {
    // Navbar
    brand: string;
    startTrial: string;
    navHome: string;
    navServices: string;
    navTemplates: string;
    navProjects: string;
    navBlog: string;
    navPricing: string;
    
    // Hero
    aiPowered: string;
    heroTitlePart1: string;
    heroTitlePart2: string;
    heroTitlePart3: string;
    heroSubtext: string;
    exploreStore: string;
    viewProjects: string;
    buyTemplate: string;
    
    // CategoryListing
    exploreTemplates: string;
    curatedDesigns: string;
    searchPlaceholder: string;
    all: string;
    moveToCart: string;
    
    // Features / Services
    platformFeatures: string;
    serviceTitle1: string;
    serviceTitle2: string;
    serviceDesc: string;
    feat1Title: string;
    feat1Desc: string;
    feat2Title: string;
    feat2Desc: string;
    feat3Title: string;
    feat3Desc: string;
    quoteZalo: string;

    // AI Consultation
    aiConsultationLabel: string;
    aiConsultationTitle1: string;
    aiConsultationTitle2: string;
    aiConsultationDesc: string;
    aiPlaceholder: string;
    aiOnline: string;
    aiChip1: string;
    aiChip2: string;
    aiChip3: string;
    aiChip4: string;
    aiChip5: string;

    // Footer
    footerDesc: string;
    footerCol1: string;
    footerCol2: string;
    footerCol3: string;
    footerRights: string;
    footerLinks: {
      allTemplates: string;
      newReleases: string;
      freeToUse: string;
      bestSellers: string;
      docs: string;
      blog: string;
      community: string;
      helpCenter: string;
      aboutUs: string;
      careers: string;
      press: string;
      legal: string;
    };
  };
};

const translations: Translations = {
  en: {
    brand: "NovaWeb AI",
    startTrial: "Dùng Thử Miễn Phí",
    navHome: "Home",
    navServices: "Services",
    navTemplates: "Templates",
    navProjects: "Projects",
    navBlog: "Blog",
    navPricing: "Pricing",
    aiPowered: "/ ENTERPRISE DESIGN & DEV",
    heroTitlePart1: "CRAFTING",
    heroTitlePart2: "ELITE WEBSITES",
    heroTitlePart3: "to elevate your brand.",
    heroSubtext: "Own a world-class UX/UI platform with lightning-fast speed and maximum security. We deliver full source code and admin access, giving you 100% control over your digital ecosystem. Trusted by 500+ businesses.",
    exploreStore: "Get consultation and quote",
    viewProjects: "View 150+ projects",
    buyTemplate: "Buy Template",
    exploreTemplates: "Explore Templates",
    curatedDesigns: "Curated high-end designs generated by AI.",
    searchPlaceholder: "Search templates...",
    all: "All",
    moveToCart: "Move to Cart",
    
    // Features / Services
    platformFeatures: "03 — OUR SERVICES",
    serviceTitle1: "WEBSITE & WEB APP",
    serviceTitle2: "PROFESSIONAL",
    serviceDesc: "Build fully functional, personalized websites tailored to your business model and optimized to maximize customer trust and conversion rates.",
    feat1Title: "Custom Website",
    feat1Desc: "Corporate websites, e-commerce, landing pages or portfolios with unique UI, industry-specific content, and custom features.",
    feat2Title: "Custom Web App",
    feat2Desc: "Develop management web apps, dashboards, booking systems, or internal portals with fast, intuitive, and scalable interfaces.",
    feat3Title: "SEO & Conversion",
    feat3Desc: "Optimize heading structures, loading speed, schemas, sitemaps, sales content, and contact forms to rank higher effortlessly.",
    quoteZalo: "Quote via Zalo",

    // AI Consultation
    aiConsultationLabel: "04 — AI CONSULTATION",
    aiConsultationTitle1: "DESCRIBE THE WEBSITE",
    aiConsultationTitle2: "YOU NEED",
    aiConsultationDesc: "Discuss costs, features, SEO, or ideas — NovaWeb AI is ready to assist.",
    aiPlaceholder: "Ask about pricing, features, SEO, process, or describe your project...",
    aiOnline: "Online",
    aiChip1: "Pricing estimation",
    aiChip2: "Corporate Website",
    aiChip3: "E-commerce",
    aiChip4: "Web App",
    aiChip5: "SEO Google",


    // Footer
    footerDesc: "The ultimate AI website builder. Generate, customize, and launch beautiful, high-converting websites in seconds.",
    footerCol1: "Templates",
    footerCol2: "Resources",
    footerCol3: "Company",
    footerRights: "© 2026 NovaWeb. All rights reserved.",
    footerLinks: {
      allTemplates: "All Templates",
      newReleases: "New Releases",
      freeToUse: "Free to Use",
      bestSellers: "Best Sellers",
      docs: "Documentation",
      blog: "Blog",
      community: "Community",
      helpCenter: "Help Center",
      aboutUs: "About Us",
      careers: "Careers",
      press: "Press",
      legal: "Legal"
    }
  },
  vi: {
    brand: "NovaWeb AI",
    startTrial: "Liên hệ Zalo để báo giá",
    navHome: "Trang chủ",
    navServices: "Dịch vụ",
    navTemplates: "Kho giao diện",
    navProjects: "Dự án",
    navBlog: "Blog",
    navPricing: "Bảng giá",
    aiPowered: "/ THIẾT KẾ WEB DOANH NGHIỆP",
    heroTitlePart1: "KIẾN TẠO",
    heroTitlePart2: "WEB ĐỈNH CAO",
    heroTitlePart3: "khẳng định vị thế thương hiệu.",
    heroSubtext: "Sở hữu nền tảng website chuẩn UX/UI quốc tế, tốc độ siêu tốc và bảo mật tuyệt đối. Cam kết bàn giao toàn bộ mã nguồn giúp bạn làm chủ 100% hệ sinh thái số. Hơn 500+ doanh nghiệp đã tin chọn.",
    exploreStore: "Nhận tư vấn và báo giá",
    viewProjects: "Xem 150+ dự án",
    buyTemplate: "Mua Giao Diện",
    exploreTemplates: "Khám Phá Giao Diện",
    curatedDesigns: "Những thiết kế cao cấp được chọn lọc bởi AI.",
    searchPlaceholder: "Tìm kiếm giao diện...",
    all: "Tất cả",
    moveToCart: "Thêm Vào Giỏ",
    
    // Features / Services
    platformFeatures: "03 — DỊCH VỤ CỦA CHÚNG TÔI",
    serviceTitle1: "WEBSITE & WEB APP",
    serviceTitle2: "CHUYÊN NGHIỆP",
    serviceDesc: "Làm website đầy đủ tính năng, cá nhân hóa theo mô hình kinh doanh và tối ưu để khách hàng dễ tin tưởng hơn.",
    feat1Title: "Website theo yêu cầu",
    feat1Desc: "Website doanh nghiệp, bán hàng, landing page hoặc giới thiệu dịch vụ với giao diện riêng, nội dung đúng ngành và tính năng theo nhu cầu.",
    feat2Title: "Web App theo yêu cầu",
    feat2Desc: "Xây web app quản lý, dashboard, đặt lịch, bán hàng hoặc cổng nội bộ với giao diện nhanh, dễ dùng và dễ mở rộng.",
    feat3Title: "SEO & tối ưu chuyển đổi",
    feat3Desc: "Tối ưu cấu trúc heading, tốc độ tải, schema, sitemap, nội dung bán hàng và form liên hệ để website dễ lên top hơn.",
    quoteZalo: "Báo giá qua Zalo",

    // AI Consultation
    aiConsultationLabel: "04 — TƯ VẤN BẰNG AI",
    aiConsultationTitle1: "MÔ TẢ WEBSITE",
    aiConsultationTitle2: "BẠN CẦN",
    aiConsultationDesc: "Trao đổi về chi phí, tính năng, SEO hoặc ý tưởng — NovaWeb AI tư vấn ngay",
    aiPlaceholder: "Hỏi về giá, tính năng, SEO, quy trình hoặc mô tả website bạn cần...",
    aiOnline: "Online",
    aiChip1: "Báo giá phù hợp",
    aiChip2: "Website doanh nghiệp",
    aiChip3: "Website bán hàng",
    aiChip4: "Web App",
    aiChip5: "SEO Google",


    // Footer
    footerDesc: "Trình tạo website AI tối thượng. Tạo, tùy chỉnh và triển khai các trang web tuyệt đẹp, tỷ lệ chuyển đổi cao chỉ trong vài giây.",
    footerCol1: "Giao Diện",
    footerCol2: "Tài Nguyên",
    footerCol3: "Công Ty",
    footerRights: "© 2026 NovaWeb. Đã đăng ký bản quyền.",
    footerLinks: {
      allTemplates: "Tất cả giao diện",
      newReleases: "Mới ra mắt",
      freeToUse: "Sử dụng miễn phí",
      bestSellers: "Bán chạy nhất",
      docs: "Tài liệu hướng dẫn",
      blog: "Blog chia sẻ",
      community: "Cộng đồng",
      helpCenter: "Trung tâm hỗ trợ",
      aboutUs: "Về chúng tôi",
      careers: "Tuyển dụng",
      press: "Báo chí",
      legal: "Pháp lý"
    }
  },
};

interface LanguageContextProps {
  lang: Language;
  setLang: (lang: Language) => void;
  t: Translations["en"];
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("vi"); // Default to Vietnamese based on user's request context

  const value = {
    lang,
    setLang,
    t: translations[lang],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
};
